### PR TITLE
ENH: Adds castra support

### PR DESCRIPTION
**Pull request by llllllllll**
ping @jcrist

### CODE REVIEW

**Comment by jcrist** [comment]
I'm not super familiar with odo, but on first glance this looks good from the castra side of things.

**Comment by mrocklin** [comment]
As a warning Castra is an experimental codebase and the API may change significantly and without warning.

**Comment by llllllllll** [comment]
I understand the state of castra right now. I wanted to try prototyping using dask with a system that already uses odo so I figured I could push this back into odo.
Maybe we could have these functions raise `ExperimentalWarning` or something that alerts the user that this might not work with their version of castra.

**Comment by llllllllll** [comment]
ping @cpcloud , is this okay to merge?

**Comment by cpcloud** [comment]
Please add this feature to the experimental section with a note saying that castra itself is subject to change formats without warning.

**Comment by cpcloud** [comment]
Also a couple of follow ups to think about but not necessary for this PR:

1. Categorical dshapes which are on the way. Castra becomes much more useful when categoricals can be used.
2. Adding `castra://` to the resource dispatcher.

**Comment by cpcloud** [comment]
Maybe add an X failing test for odoing a castra to a dataframe when the castra has categories.

**Comment by cpcloud** [comment]
Then good to merge

**Comment by cpcloud** [comment]
@llllllllll anything left to do here?

**Comment by llllllllll** [comment]
I don't think I have gotten to the feedback you left about the whatsnew or tests. I will implement that before merging unless you need this now.

**Comment by llllllllll** [comment]
Also, I should test on the newest version of castra. I haven't touched this in a while.

**Comment by cpcloud** [comment]
cool, no rush

**Comment by llllllllll** [comment]
Quick question about the resource dispatcher, should we have `castra://` and `.castra`? Currently I only have the `.castra`

**Comment by cpcloud** [comment]
probably should have both since presumably not every `Castra`'s file name will end in `.castra`

**Comment by llllllllll** [comment]
I forgot about this. Just pushed the updates and rebased but looks like dask tests are failing ;_;

**Comment by cowlicks** [comment]
@llllllllll I'll look at the dask tests today. The failures are not a result of your PR.

**Comment by kwmsmith** [comment]
@llllllllll I'm holding off on adding new backends for the 0.4.1 release -- when you get a chance, could you look into the Travis-CI failure?

**Comment by llllllllll** [comment]
Sure thing. I also need to rebase

**Comment by llllllllll** [comment]
I have been told to not use castra anymore so it is probably not worth merging this.

**Pull request closed without merging**
