### PR TITLE
Tweaks and version updates for 0.4.1 release.

### PR DESCRIPTION
**Pull request by kwmsmith**

### CODE REVIEW

**Comment by llllllllll** [comment]
how do the recommended requirements differ from the requirements?

**Comment by kwmsmith** [comment]
> how do the recommended requirements differ from the requirements?

`requirements.txt` is a subset of `recommended-requirements`.  The recommended reqs include optional backends.

**Comment by llllllllll** [comment]
Okay, should this be exposed as `odo[all]` or another `extra_requires` target?

**Comment by kwmsmith** [comment]
@llllllllll good suggestion, I added an `all` `extra_requires` target.

**Comment by llllllllll** [comment]
Awesome, thanks

**Pull request merged**
