### PR TITLE
BUG: infer_header was not forwarded the encoding

### PR DESCRIPTION
**Pull request by llllllllll**
https://github.com/wavexx/gtabview/issues/17

### CODE REVIEW

**Comment by cpcloud** [comment]
Can you add a test for this?

**Comment by llllllllll** [comment]
Sure thing

**Comment by llllllllll** [comment]
I just made sure the `encoding.csv` file was `latin-1` and then added some non-utf code in there. This failed an existing test on master, we previously were using the intersection of utf-8 and latin-1 so it was fine.

**Comment by cpcloud** [comment]
cool

**Comment by cpcloud** [comment]
merge on pass

**Comment by llllllllll** [comment]
Hmm, the test failure shows are not handing some sql encoding stuff correctly either. Looking into it.

**Comment by llllllllll** [comment]
I am having trouble figuring out how to get sqlite and sqlalchemy to actually support latin1. Docs seems unclear.

**Comment by cpcloud** [comment]
@llllllllll the travis failure is because you've written an encoded character in python code without telling python what encoding to use to read the file.

**Comment by cpcloud** [comment]
write it as bytes and then call encode on it

**Comment by llllllllll** [comment]
Ah, will be explicit about the encoding for py2 then.

**Comment by cpcloud** [comment]
i think you can just do `b'the_chars'.decode('latin1')` and will work on all python versions

**Comment by cpcloud** [comment]
@llllllllll can we salvage anything here? or should this be closed?

**Comment by llllllllll** [comment]
The csv stuff in here was correct; however, I realized that there were some issues with encoding in sqlite. We could probably rip the the sql stuff out since the original issue I was going to fix was the csv encoding problems

**Pull request closed without merging**
