### PR TITLE
Simulation mode added to odo/into

### PR DESCRIPTION
**Pull request by octophat**
This change adds a simulate parameter to the into functions, which default to False, and are passed down implicitly from the odo function's kwargs. This should be useful when adding new backends, debugging problems, or optimizing conversion paths, to both enable path information to be returned in a usable format, and to provide a means for testing without having to actually initiate data conversions.

When simulate=True, instead of executing the functions returned by append and convert and returning the resulting data object, odo will create a new Path object, populate it with information about the conversion path(s) returned by append and convert, and return the Path.

This object can be printed for a human-readable string representation of the types, functions, and code that will be involved in the conversion, or a process can reference the information in the Path object's attributes.

### CODE REVIEW

**Comment by octophat** [comment]
This addresses and resolves #265.

**Comment by mrocklin** [comment]
Cool.  My first impression is that this adds a lot of code into what was previously a pretty small file/function that just dispatched off to more complex functions.  I wonder if there is a way to separate this simulation work out from `into.py` and into another file.  Similarly I wonder if we could pull out the code currently in the `into` functions to some separate `simulate` function, perhaps adding a small call to `into` to dispatch to that function as appropriate.  This helps by releasing future developers who aren't interested in simulate from having to sift through it to understand `into`.

**Comment by octophat** [comment]
That's fair, let me see if I can split this off into a separate simulate.py.

On the Travis errors, I can fix the importlib error in 2.6, but the dask and bcolz errors seem unrelated to my changes... am I right?

**Comment by octophat** [comment]
I think the last two commits keep `into.py` clean and get the simulation option working under Python 2 and 3. Let me know if there are any other changes to the functionality or style you would like.

**Comment by octophat** [comment]
@cpcloud, I thought a little last night about having the simulation functionality implemented in a separate function (`odo.simulate()`) vs. as a parameter in the existing odo function (`odo.odo(simulate=True)`). I think that would require us to duplicate all the same multiple dispatch logic in into.py, to parse out the different types of inputs that the function could receive. It seems better to have it as a parameter to `odo.into` (and by extension, `odo.odo`) to piggyback off the existing logic. I think @mrocklin's concerns about cluttering up into.py should be OK now with the logic moved into simulate.py and the Path object.

I'm fine with changing the structure of the Path object or how it's represented, but it seems like invoking this through the `simulate=True` parameter causes the least duplication of code.

**Comment by cpcloud** [comment]
@octophat taking a look at this now

**Comment by octophat** [comment]
Apologies for not coming back to this sooner - I've been working on a different project unrelated to odo lately, but I have some time around the holidays now to come back to this a little wiser. :)

I'm going to withdraw this pull request for now as I want to take a fresh look at it, looking at the broader applicability of how odo can work in testing environments where you don't want to actually run conversions but need to verify that odo will take a specific path or run a given function. I think this is needed more than ever, but there'll be a better way to do it than the code I had here. I'll capture my thoughts in #265 and welcome any feedback.

**Pull request closed without merging**
