### PR TITLE
discover should not consume first element from chunks

### PR DESCRIPTION
**Pull request by llllllllll**

### CODE REVIEW

**Comment by llllllllll** [comment]
How do I check what version of `toolz` this ran with, looks like it couldn't get the `peek` func

**Comment by cpcloud** [comment]
why does the conda output look so horrible?

screen shot 2015-08-07 at 13 59 33

**Comment by llllllllll** [comment]
no idea, does it not normally look like that?

**Comment by cpcloud** [comment]
no it usually is newline delimited

**Comment by llllllllll** [comment]
Any ideas on this, can't repro

**Comment by llllllllll** [comment]
Looks like the newest version of toolz doesn't have 2.6 or 3.3 conda packages (https://github.com/pytoolz/toolz/issues/269)

**Comment by mrocklin** [comment]
cc @ilanschnell .  Is there a reason why we would have built recent packages for `toolz` on 2.7 and 3.4 but not 2.6 and 3.3?

**Comment by ilanschnell** [comment]
Yes.  Because we stopped supporting Python 2.6 and 3.3.  This means we are not building new (or updating old) Python packages ones against Python 2.6 and 3.3, unless requested by a customer.

**Comment by mrocklin** [comment]
Hrm, can I request continued Python 2.6 and 3.3 builds for toolz?  The library is simple enough that it should hopefully not be an extra burden.  Alternatively would toolz be appropriate for a noarch build?

**Comment by ilanschnell** [comment]
Why does odo still care about Python 2.6 and 3.3?

**Comment by mrocklin** [comment]
Presumably people are still on 2.6.  I don't have a good view into this though.  

Note that `toolz` is depended upon far more widely than `odo`.  Even if `odo` doesn't add pressure for 2.6 there might be sufficient pressure from external projects.

**Pull request merged**
