### PR TITLE
Use boto3 from conda and disable pip --upgrade.

### PR DESCRIPTION
**Pull request by skrah**

### CODE REVIEW

**Comment by skrah** [comment]
The Travis CI failures occur when pip pulls in boto3-1.4.0-py2.py3-none-any.whl.  Using boto3 from conda "fixes" the issue.

**Comment by skrah** [comment]
@kwmsmith I think this could be a reasonable fix until someone more familiar with boto3 tracks down the boto3 version issues.

**Comment by skrah** [comment]
N.B. I cannot reproduce this at home either with boto3-1.4.0, so it will remain a CI mystery. :)

**Comment by kwmsmith** [comment]
@skrah thank you for getting to the bottom of this!

**Pull request merged**
