### PR TITLE
Update odo library to use recent version of sqlalchemy-redshift library.

### PR DESCRIPTION
**Pull request by jjsloboda**

### CODE REVIEW

**Comment by kwmsmith** [comment]
@jjsloboda thanks for the PR; apologies for the delay.

Please update the `.travis.yml` file to use this renamed library; once that's done and the tests pass, will review and merge.

**Comment by jjsloboda** [comment]
Made the requested change, however the Travis CI build failed and it is not clear to me why, especially since http://github.com/graingert/redshift_sqlalchemy actually just redirects to the new url.

Reconstructed the Travis test setup locally with docker using the instructions listed here: https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image
And I am unable to replicate the failures (with TRAVIS_PYTHON_VERSION="2.7" and SPARK_VERSION="1.4")

**Comment by kwmsmith** [comment]
@jjsloboda I merged a workaround for the paramiko ssh test issues on Py2; please merge / rebase on master, thanks!

**Comment by jjsloboda** [comment]
@kwmsmith Thanks; done. Core tests pass now.

**Pull request closed without merging**
