### PR TITLE
TST: Add appveyor testing

### PR DESCRIPTION
**Pull request by thequackdaddy**
Hello,

xref #522 

I've put together appveyor.yml for this. 

A few limitations:

* The point of this is to write some mssql tests. Haven't started that yet. 
* I can't get mongodb or mysql to work on appveyor. Going to confess I don't know that much about them however. I can start the service and add them to PATH, but that's about the limit of what I can figure out. 
* I can't successfully run `pip install -e .[ci]`. There's a lot that needs to build and it takes a long, long time and some of it (h5py and cryptography especially) just doesn't cooperate. So instead I just pull the pre-compiled binaries from `conda`. 

Here's the test result of this:

https://ci.appveyor.com/project/thequackdaddy/odo

Let me know if there's interest for this. 

Thanks.

### CODE REVIEW

**Comment by necaris** [comment]
I'd love to add this, to add CI for MSSQL -- I've set up an AppVeyor project at https://ci.appveyor.com/project/blaze/odo but I'm not sure how to integrate this branch and see the test results...

**Comment by thequackdaddy** [comment]
I re-pushed the commit. Looks like its starting now.

**Comment by necaris** [comment]
This looks great -- tests are passing, well done! Did you want to add the MSSQL testing in this PR or in a follow-up?

**Comment by thequackdaddy** [comment]
I was thinking follow-up. 

I've had issues with a lot of the mssql specific datatypes (e.g., `bit`, `money`, `datetimeoffset`) not playing well with python so I need to figure out how to get that to work.

**Comment by necaris** [comment]
Awesome, thank you!

**Pull request merged**
