### PR TITLE
Check directory existence and properly deal with patterned directories

### LINKED ISSUE #151: Directory of gzipped CSVs is broken
```
mkdir test
cd test
$ echo -en "a,b\n1,2\n3,4" > a.csv
$ echo -en "a,b\n1,2\n3,4\n5,6" > b.csv
$ gzip < *.csv > ab.csv.gz
$ cd ..
$ ipython
In [1]: df = odo('test/*.csv.gz', pd.DataFrame)
KeyError: <class 'odo.directory.Directory(CSV)'>
```

### PR DESCRIPTION
**Pull request by cpcloud**
closes #151 
- [x] asserts that the directory of files must exist when calling resource on it
- [x] patterns like `test/*.csv` don't iterate over everything in the directory
- [x] provides way to convert a `Directory` of CSVs into `chunks(DataFrame)`
- [ ] testing on hdfs

### CODE REVIEW

**Comment by cpcloud** [comment]
Alternatively, we could make everything that contains a glob pattern mean `chunks`

**Comment by cpcloud** [comment]
pushing to 0.3.3

**Comment by llllllllll** [comment]
If someone wants to own this please reopen.

**Comment by ethanluoyc** [comment]
This is still occurring on version 0.5.0 (the latest development version?)
It can be reproduced with the same procedure

**Pull request closed without merging**
