### PR TITLE
Issue #465: Fix datashape discovery if dshape=None.

### LINKED ISSUE #465: conversion from `itertools.chain` to DataFrame raises
```python
In [29]: odo.odo(itertools.chain(['a', 'b']), pd.DataFrame)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-d11e25f205aa> in <module>()
----> 1 odo.odo(itertools.chain(['a', 'b']), pd.DataFrame)

/Users/ksmith/work/odo/odo/odo.py in odo(source, target, **kwargs)
     89     odo.append.append      - Add things onto existing things
     90     """
---> 91     return into(target, source, **kwargs)

/Users/ksmith/anaconda/envs/blaze-3.5/lib/python3.5/site-packages/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    162             self._cache[types] = func
    163         try:
--> 164             return func(*args, **kwargs)
    165
    166         except MDNotImplementedError:

/Users/ksmith/work/odo/odo/into.py in wrapped(*args, **kwargs)
     41             raise TypeError('dshape argument is not an instance of DataShape')
     42         kwargs['dshape'] = dshape
---> 43         return f(*args, **kwargs)
     44     return wrapped
     45

/Users/ksmith/work/odo/odo/into.py in into_type(a, b, dshape, **kwargs)
     51         if dshape is None:
     52             dshape = discover(b)
---> 53     return convert(a, b, dshape=dshape, **kwargs)
     54
     55

/Users/ksmith/work/odo/odo/core.py in __call__(self, *args, **kwargs)
     42
     43     def __call__(self, *args, **kwargs):
---> 44         return _transform(self.graph, *args, **kwargs)
     45
     46

/Users/ksmith/work/odo/odo/core.py in _transform(graph, target, source, excluded_edges, ooc_types, **kwargs)
     58     try:
     59         for (A, B, f) in pth:
---> 60             x = f(x, excluded_edges=excluded_edges, **kwargs)
     61         return x
     62     except NotImplementedError as e:

/Users/ksmith/work/odo/odo/convert.py in iterator_to_DataFrame_chunks(seq, chunksize, **kwargs)
    219             yield convert(pd.DataFrame, [], **kwargs)
    220     else:
--> 221         df = convert(pd.DataFrame, first, **kwargs)
    222         df1, n1 = mkindex(df, 0)
    223

/Users/ksmith/work/odo/odo/core.py in __call__(self, *args, **kwargs)
     42
     43     def __call__(self, *args, **kwargs):
---> 44         return _transform(self.graph, *args, **kwargs)
     45
     46

/Users/ksmith/work/odo/odo/core.py in _transform(graph, target, source, excluded_edges, ooc_types, **kwargs)
     58     try:
     59         for (A, B, f) in pth:
---> 60             x = f(x, excluded_edges=excluded_edges, **kwargs)
     61         return x
     62     except NotImplementedError as e:

/Users/ksmith/work/odo/odo/convert.py in list_to_numpy(seq, dshape, **kwargs)
    168             not isscalar(dshape)):
    169         seq = list(map(tuple, seq))
--> 170     return np.array(seq, dtype=dshape_to_numpy(dshape))
    171
    172

/Users/ksmith/work/odo/odo/numpy_dtype.py in dshape_to_numpy(ds)
     91         ])
     92     else:
---> 93         return unit_to_dtype(ds)
     94
     95

/Users/ksmith/work/odo/odo/numpy_dtype.py in unit_to_dtype(ds)
     48     if ds == string:
     49         return np.dtype('O')
---> 50     return to_numpy_dtype(ds)
     51
     52

/Users/ksmith/work/datashape/datashape/coretypes.py in to_numpy_dtype(ds)
   1277     """ Throw away the shape information and just return the
   1278     measure as NumPy dtype instance."""
-> 1279     return to_numpy(ds.measure)[1]
   1280
   1281

AttributeError: 'NoneType' object has no attribute 'measure'
```

### PR DESCRIPTION
**Pull request by skrah**
@kwmsmith This fixes #465.  If you have time to merge this, it might be easier to finish work on https://github.com/blaze/blaze/pull/1559 .

### CODE REVIEW

**Comment by kwmsmith** [comment]
@skrah I restarted the travis-ci job, but it still fails -- can you look into the failures?

**Comment by skrah** [comment]
@kwmsmith I cannot reproduce this failure on my machine.  I could force a similar failure by leaving a ```build``` directory in the tree (see #468), but that isn't the cause here.

**Comment by kwmsmith** [comment]
@skrah can you merge in `master` to get the travis-ci fixes in this PR?

**Comment by skrah** [comment]
@kwmsmith It's in already: I rebased the PR onto the latest master -- I got into that habit over at libdynd where it was the preferred way.

**Comment by kwmsmith** [comment]
@skrah great, thanks.

**Pull request merged**
