### PR TITLE
Implement `raise_on_errors` kwarg for `drop`

### PR DESCRIPTION
**Pull request by cpcloud**
cc @jreback

### CODE REVIEW

**Comment by cpcloud** [comment]
@llllllllll can you give this a review when you get a chance?

**Comment by llllllllll** [comment]
Implementation looks good, I just feel like the name is not very clear. People might get confused about which errors we are raising on. Maybe something like `ignore_nonexistent`.

**Comment by kwmsmith** [comment]
@llllllllll this PR is pretty stale -- is it still relevant?

Regarding the argument name: other ways I've seen to approach this is to have an `errors` argument that is `'ignore'` by default, and can be set to `'raise'`, `'warn'`, etc, which provide more user control.  Thoughts?

**Comment by llllllllll** [comment]
I like the raise, warn, ignore pattern; however, I prefer enums over strings. Harder to get wrong. Also, I think only raise or warn are sane defaults often

**Pull request closed without merging**
