### PR TITLE
Fix cost of converting a Select to a scalar value

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by cpcloud** [comment]
@cowlicks this fixes the issue properly which was that the cost of getting a scalar out of a select statement from sqlalchemy was actually higher than getting out a series or dataframe.

**Comment by cowlicks** [comment]
@cpcloud Do you think, the costs for `dask_to_other` should be higher? I thought they should be comparable with `select_to_base`?

**Comment by cpcloud** [comment]
@cowlicks Yep, that makes sense. I'll update accordingly.

**Comment by cowlicks** [comment]
Thanks @cpcloud

**Pull request merged**
